sudo: required

services:
  - docker

before_install:
  - docker build -t vijayrajan23/redserver -f redis/Dockerfile.dev
  - docker build -t vijayrajan23/oneserver -f one/Dockerfile.dev
  - docker build -t vijayrajan23/proxyserver -f gate/Dockerfile.dev

script:
  - pass
  