sudo: required

services:
  - docker

before_install:
  - docker build -t vijayrajan23/redserver redis/Dockerfile.dev .
  - docker build -t vijayrajan23/oneserver one/Dockerfile.dev .
  - docker build -t vijayrajan23/proxyserver gate/Dockerfile.dev .

script:
  - pass
  