sudo: required

services:
  - docker

before_install:
  - docker login -u "$docker_username" -p "$docker_password"
  - docker build -f ./redis/Dockerfile.dev . -t vijayrajan23/redis
  - docker build -f ./one/Dockerfile.dev . -t vijayrajan23/one
  - docker build -f ./gate/Dockerfile.dev . -t vijayrajan23/gate

script:
  - docker push vijayrajan23/redis
  - docker push vijayrajan23/one
  - docker push vijayrajan23/gate
  - docker-compose build 