sudo: required

services:
  - docker

before_install:
<<<<<<< HEAD
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker build -f ./redis/Dockerfile.dev . -t vijayrajan23/redis:vr1
  - docker build -f ./one/Dockerfile.dev . -t vijayrajan23/one:vr1
  - docker build -f ./gate/Dockerfile.dev . -t vijayrajan23/revers:vr1

script:
  - docker push vijayrajan23/redis:vr1
  - docker push vijayrajan23/one:vr1
  - docker push vijayrajan23/revers:vr1
=======
  - docker login -u "$docker_username" -p "$docker_password"
  - docker build -f ./redis/Dockerfile.dev . -t vijayrajan23/redis
  - docker build -f ./one/Dockerfile.dev . -t vijayrajan23/one
  - docker build -f ./gate/Dockerfile.dev . -t vijayrajan23/gate

script:
  - docker push vijayrajan23/redis
  - docker push vijayrajan23/one
  - docker push vijayrajan23/gate
  - docker-compose build 
>>>>>>> d4cd7bbadee4b3ce923a155eef677e6c0a5c6241
