sudo: required

services:
  - docker

before_install:
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker build -f ./redis/Dockerfile.dev . -t vijayrajan23/redis:vr1
  - docker build -f ./one/Dockerfile.dev . -t vijayrajan23/one:vr1
  - docker build -f ./gate/Dockerfile.dev . -t vijayrajan23/revers:vr1

script:
  - docker push vijayrajan23/redis:vr1
  - docker push vijayrajan23/one:vr1
  - docker push vijayrajan23/revers:vr1