sudo: required

services:
  - docker

before_install:
  - docker build -t vijayrajan23/redserver Dockerfile.dev redis/.
  - docker build -t vijayrajan23/oneserver Dockerfile.dev one/.
  - docker build -t vijayrajan23/proxyserver Dockerfile.dev gate/.

script:
  - pass
  