sudo: required

services:
  - docker

before_install:
  - docker build -f redis/Dockerfile.dev -t vijayrajan23/redserver .
  - docker build -f one/Dockerfile.dev -t vijayrajan23/oneserver .
  - docker build -f gate/Dockerfile.dev -t vijayrajan23/proxyserver .

script:
  - pass
  