sudo: required

services:
  - docker

before_install:
  - docker build -f redis/Dockerfile.dev .
  - docker build -f one/Dockerfile.dev .
  - docker build -f gate/Dockerfile.dev .

script:
  - pass
  